require('nvim-treesitter.configs').setup {
  ensure_installed = {
    "c_sharp",
    "rst",
    "fennel",
    "teal",
    "ql",
    "c",
    "pascal",
    "bash",
    "comment",
    "html",
    "jsdoc",
    "rego",
    "hcl",
    "sparql",
    "glimmer",
    "clojure",
    "commonlisp",
    "cpp",
    "godot_resource",
    "javascript",
    "cuda",
    "turtle",
    "regex",
    "glsl",
    "dockerfile",
    "svelte",
    "dot",
    "rust",
    "ocamllex",
    "fusion",
    "css",
    "ledger",
    "bibtex",
    "elvish",
    "cooklang",
    "solidity",
    "python",
    "query",
    "cmake",
    "vala",
    "gomod",
    "zig",
    "gowork",
    "scheme",
    "graphql",
    "pioasm",
    "ruby",
    "typescript",
    "rasi",
    "perl",
    "make",
    "prisma",
    "scala",
    "fish",
    "json",
    "supercollider",
    "php",
    "http",
    "java",
    "llvm",
    "kotlin",
    "hocon",
    "hjson",
    "json5",
    "julia",
    "vim",
    "norg",
    "lua",
    "toml",
    "latex",
    "beancount",
    "erlang",
    "r",
    "devicetree",
    "elixir",
    "pug",
    "gdscript",
    "lalrpop",
    "gleam",
    "tsx",
    "surface",
    "jsonc",
    "scss",
    "eex",
    "heex",
    "yaml",
    "ocaml",
    "yang",
    "go",
    "astro",
    "ninja",
    "ocaml_interface",
    "wgsl",
    "nix",
    "tlaplus",
    "dart",
    "vue",
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = false,
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<CR>",
      node_incremental = ".",
      scope_incremental = "<CR>",
      node_decremental = ",",
    },
  },
  textobjects = {
    select = {
      enable = true,
      lookahead = true,
      keymaps = {
        ["af"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ac"] = "@class.outer",
        ["ic"] = "@class.inner",
      },
    },
  },
  textsubjects = {
    enable = true,
    keymaps = {
      ['s'] = 'textsubjects-smart',
      [';'] = 'textsubjects-container-outer',
      ['i;'] = 'textsubjects-container-inner',
    }
  },
}
